### ISSUE TITLE
Add Redis to the list of technologies that requiere open alternatives

### ISSUE THREAD

**Issue by ricardomiron** [DPGAlliance/dpg-resources#15]
Redis is moving away from the BSD 3-Clause License to a dual-license model, offering developers the choice between the [Redis Source Available License](https://redis.com/legal/rsalv2-agreement/) version 2 (RSALv2) or the Server-Side Public License version 1 (SSPLv1).

These new licenses are incompatible with the Open Source Definition and not OSI-approved licenses, making Redis source available but not open source anymore for future versions. We will start recommending [Redict](https://redict.io/) or [Valkey](https://valkey.io/) as open alternatives.

**Comment by BolajiAyodeji** [comment]
This is resolved now in #19 @ricardomiron. Thank you.
