### ISSUE TITLE
Update documentation around Openness and Usability criteria for Open Data and Open Content DPGs

### ISSUE THREAD

**Issue by ricardomiron** [DPGAlliance/dpg-resources#16]
We recently introduced clearer requirements for what constitutes eligible open data and open content collections as DPGs and the level of openness they must have after expert and community input [here](https://github.com/DPGAlliance/DPG-Standard/issues/186).

This should be reflected in the DPG Wiki and any other relevant place.

**Comment by BolajiAyodeji** [comment]
This is resolved now in the DPG Wiki @ricardomiron. Thank you.
