### ISSUE TITLE
Split open content licenses in DPG Wiki

### ISSUE THREAD

**Issue by ricardomiron** [DPGAlliance/dpg-resources#17]
**DPG Wiki**: Similar to how OKF has [open data recommended and other conformant licenses](https://opendefinition.org/licenses/), we can divide open content licenses into recommended/ encouraged (more permissive) and those who have Non-commercial restrictions.

- Recommended licenses
- Other acceptable licenses

**Comment by BolajiAyodeji** [comment]
This is resolved now in the DPG Wiki @ricardomiron. Thank you.
