### ISSUE TITLE
Add section on Documentation

### ISSUE THREAD

**Issue by lacabra** [DPGAlliance/DPG-Resources#3]
Having good documentation in open source projects is a critical feature, a dealbreaker in most cases for others use, adopt and adapt any given project. As a result, it is important to provide ample resources in this area for digital public goods to build great documentation for their projects.

Potential resources include:
- [The Good Docs Project](https://thegooddocsproject.dev/)
- [DocBuilds](https://www.docbuilds.com/)
- Some examples of projects with outstanding documentation, some ideas from [here](https://unicef.github.io/inventory/documentation/hall-of-fame/).

**Comment by christer-io** [comment]
Will add this to the repo and website. Tnx!
